name: Deploy MultiDocker

on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Detect which directories have changed
      - name: Detect changed files
        id: changes
        run: |
          echo "Checking changed directories..."
          git fetch origin main
          # Compare with the previous commit on main
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | cut -d/ -f1 | sort -u)
          echo "Changed directories: $CHANGED_DIRS"
          echo "dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      # --- CLIENT ---
      - name: Build and test client
        if: contains(steps.changes.outputs.dirs, 'client')
        run: |
          echo "Building and testing client..."
          docker build -t benjaminjm112/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true benjaminjm112/react-test npm test
          docker build -t benjaminjm112/multi-client ./client
          docker push benjaminjm112/multi-client

      # --- NGINX ---
      - name: Build nginx
        if: contains(steps.changes.outputs.dirs, 'nginx')
        run: |
          echo "Building nginx..."
          docker build -t benjaminjm112/multi-nginx ./nginx
          docker push benjaminjm112/multi-nginx

      # --- SERVER ---
      - name: Build server
        if: contains(steps.changes.outputs.dirs, 'server')
        run: |
          echo "Building server..."
          docker build -t benjaminjm112/multi-server ./server
          docker push benjaminjm112/multi-server

      # --- WORKER ---
      - name: Build worker
        if: contains(steps.changes.outputs.dirs, 'worker')
        run: |
          echo "Building worker..."
          docker build -t benjaminjm112/multi-worker ./worker
          docker push benjaminjm112/multi-worker

  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::841162669835:role/GithHUB_OIDC

      - name: Check out code
        uses: actions/checkout@v3
      - name: Generate deployment package
        run: zip deploy.zip Dockerrun.aws.json docker-compose.yml
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: multi
          environment_name: Multi-env
          region: us-east-1
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-1-841162669835 
          deployment_package: deploy.zip

      

      